Change subsystem name 'hotdesking' to 'hotdesk' and keep this consistent everywhere.

diff --git a/fdo-server b/fdo-server
--- a/fdo-server
+++ b/fdo-server
@@ -170,7 +170,7 @@ usage ()
 	echo -e ""
 	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} setup-vnc-desktop${NRML}"
 	echo -e ""
-	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} init-hotdesking${NRML}"
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} init-hotdesk${NRML}"
 	echo -e ""
 	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} init-partimag${NRML}"
 	echo -e ""
@@ -3943,7 +3943,7 @@ setup_vnc_desktop()
 	return 0
 }
 
-undo_init_hotdesking ()
+undo_init_hotdesk ()
 {
 
 	ERROR_COUNT=0
@@ -3951,7 +3951,7 @@ undo_init_hotdesking ()
 	# Destroy any created filesystems.
 	if [ ${INIT_HOTDESK_FILESYSTEMS_CREATED} = true ]
 	then
-		# Destroy the hotdesking base filesystem and any children.
+		# Destroy the hotdesk base filesystem and any children.
 		zfs destroy -rf ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS} > /dev/null 2>&1
 		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	fi
@@ -3960,9 +3960,9 @@ undo_init_hotdesking ()
 	if [ ${INIT_HOTDESK_MODIFIED} = true ]
 	then
 		# Roll back local repo to last good commit (!!!DANGEROUS!!!).
-		if [ "${COMMIT_BEFORE_INIT_HOTDESKING}" != "" ]
+		if [ "${COMMIT_BEFORE_INIT_HOTDESK}" != "" ]
 		then
-			git reset --hard ${COMMIT_BEFORE_INIT_HOTDESKING}
+			git reset --hard ${COMMIT_BEFORE_INIT_HOTDESK}
 			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 		fi
 
@@ -3973,7 +3973,7 @@ undo_init_hotdesking ()
 
 	if [ ${ERROR_COUNT} -ne 0 ]
 	then
-		echo -e "\n${LRED}ERROR:${NRML} There was at least one unexpected error undoing init-hotdesking!\n"
+		echo -e "\n${LRED}ERROR:${NRML} There was at least one unexpected error undoing init-hotdesk!\n"
 		return 2
 	fi
 
@@ -3981,16 +3981,16 @@ undo_init_hotdesking ()
 	return 0
 }
 
-init_hotdesking ()
+init_hotdesk ()
 {
 
 	INIT_HOTDESK_MODIFIED=false
 	INIT_HOTDESK_FILESYSTEMS_CREATED=false
 
-	trap 'undo_init_hotdesking exit 3' HUP INT QUIT KILL TERM
+	trap 'undo_init_hotdesk exit 3' HUP INT QUIT KILL TERM
 
 	# Save git commit reference so we can roll back changes later.
-	COMMIT_BEFORE_INIT_HOTDESKING=`git log --format=format:%H -1`
+	COMMIT_BEFORE_INIT_HOTDESK=`git log --format=format:%H -1`
 
 	ERROR_COUNT=0
 
@@ -4024,13 +4024,13 @@ init_hotdesking ()
 		return 2
 	fi
 
-	# Check that the hotdesking subsystem is not already initialised.
-	HOTDESK_SUBSYS_COMPAT=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .subsystems.hotdesking_compat`
+	# Check that the hotdesk subsystem is not already initialised.
+	HOTDESK_SUBSYS_COMPAT=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .subsystems.hotdesk_compat`
 	if [ ${?} -eq 0 ] && [ "${HOTDESK_SUBSYS_COMPAT}" != "null" ] && [ "${HOTDESK_SUBSYS_COMPAT}" != "" ]
 	then
-		echo -e "\n${LRED}ERROR:${NRML} It appears that the hotdesking subsystem is already initialised."
+		echo -e "\n${LRED}ERROR:${NRML} It appears that the hotdesk subsystem is already initialised."
 		echo -e "       Consider using the command:"
-		echo -e "       ${LBLU}${SCRIPT_NAME} dismantle-hotdesking${NRML}\n       Aborting.\n"
+		echo -e "       ${LBLU}${SCRIPT_NAME} dismantle-hotdesk${NRML}\n       Aborting.\n"
 		return 1
 	fi
 
@@ -4062,16 +4062,16 @@ init_hotdesking ()
 		done
 	fi
 
-	# Test for existing hotdesking filesystems and prompt how to proceed.
+	# Test for existing hotdesk filesystems and prompt how to proceed.
 	HOTDESK_FILESYSTEM_EXISTS="no"
 	zfs list -H ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS} > /dev/null 2>&1
 	if [ ${?} -eq 0 ]
 	then
 		echo -e "\n${ORNG}WARNING:${NRML} The ZFS filesystem '${ORNG}${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS}${NRML}' already exists!\n"
-		question_yes_no "\nIt seems as though '${NRML}init-hotdesking${LCYN}' has already been applied to this host.\nWould you like to proceed?"
+		question_yes_no "\nIt seems as though '${NRML}init-hotdesk${LCYN}' has already been applied to this host.\nWould you like to proceed?"
 		if [ "${ANSWER}" = "yes" ]
 		then
-			# Ask whether to purge, archive or reuse existing hotdesking base filesystems.
+			# Ask whether to purge, archive or reuse existing hotdesk base filesystems.
 			question_purge_archive_reuse "\nWould you like to purge, archive or reuse the existing hotdesk base filesystem\nand all it's children filesystems? [CAUTION]"
 			if [ "${ANSWER}" = "purge" ]
 			then
@@ -4080,7 +4080,7 @@ init_hotdesking ()
 			elif [ "${ANSWER}" = "archive" ]
 			then
 				NOW=`date "+%Y-%m-%d_%H-%M-%S"`
-				zfs rename -f ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS} ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS}_renamed-by-init-hotdesking-${NOW}
+				zfs rename -f ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS} ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS}_renamed-by-init-hotdesk-${NOW}
 				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 			elif [ "${ANSWER}" = "reuse" ]
 			then
@@ -4178,7 +4178,7 @@ init_hotdesking ()
 	sed -i "" "s/NIS_HOST_IP/${NIS_HOST_IP}/" configs/${HOST_NAME}/etc/rc.conf
 
 	# Add subsystems compat level and init marker to host config file.
-	${UCL_CMD} set -f configs/${HOST_NAME}/${HOST_CONF_PATH} .subsystems.hotdesking_compat "${LATEST_HOTDESK_SUBSYS_COMPAT}"
+	${UCL_CMD} set -f configs/${HOST_NAME}/${HOST_CONF_PATH} .subsystems.hotdesk_compat "${LATEST_HOTDESK_SUBSYS_COMPAT}"
 	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 	# Install host configs to the system.
@@ -4229,7 +4229,7 @@ init_hotdesking ()
 	# Create the ZFS filesystem for the root of hotdesk users home folders.
 	if [ "${HOTDESK_FILESYSTEM_EXISTS}" = "no" ]
 	then
-		echo -e "\n${YELL}Creating ZFS filesystems for hotdesking home directories...${NRML}\n"
+		echo -e "\n${YELL}Creating ZFS filesystems for hotdesk home directories...${NRML}\n"
 		INIT_HOTDESK_FILESYSTEMS_CREATED=true
 		zfs create -o mountpoint=/${HOTDESK_ROOT_FS} ${HOTDESK_POOL_NAME}/${HOTDESK_ROOT_FS}
 		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
@@ -4237,14 +4237,14 @@ init_hotdesking ()
 
 	if [ ${ERROR_COUNT} -ne 0 ]
 	then
-		echo -e "\n${LRED}ERROR:${NRML} An unexpected error occurred whilst creating hotdesking filesystems!\n"
-		undo_init_hotdesking
+		echo -e "\n${LRED}ERROR:${NRML} An unexpected error occurred whilst creating hotdesk filesystems!\n"
+		undo_init_hotdesk
 		return 2
 	fi
 
 	echo -e "\n\n${YELL}We are now ready to push the updated host configs up to the remote repo.${NRML}\n"
 	git add configs/${HOST_NAME}
-	git commit -m "Updating host after 'init-hotdesking'; ${HOST_NAME}."
+	git commit -m "Updating host after 'init-hotdesk'; ${HOST_NAME}."
 
 	if [ "${REPO_URI}" != "local" ]
 	then
@@ -8680,10 +8680,10 @@ case "${SUB_CMD}" in
 		exit ${?}
 		;;
 
-	init-hotdesking)
+	init-hotdesk)
 		# Initialise the NIS/NFS hostdesking subsystem.
 		update_local_repo
-		init_hotdesking
+		init_hotdesk
 		exit ${?}
 		;;
 
