Added new subcommand 'merge-local-repo-to-remote'.

diff --git a/fdo-server b/fdo-server
--- a/fdo-server
+++ b/fdo-server
@@ -30,7 +30,7 @@ SCRIPT_NAME=`basename $0`
 REPO_NAME="fdo-server"
 FDO_CONFIG_ROOT="/usr/local/etc/fdo"
 FDO_SERVER_SKELETON_REPO="https://github.com/freedominion-org/fdo-server.git"
-REPO_URI=`cat ${FDO_CONFIG_ROOT}/fdo-server-repo.conf 2> /dev/null`
+REPO_URI=`cat "${FDO_CONFIG_ROOT}/fdo-server-repo.conf" 2> /dev/null`
 FETCH_LATEST_SELF_URL="http://freedominion.org/"
 ESSENTIAL_PACKAGES="apcupsd axel bash bash-completion bsdadminscripts cpdup curl dmidecode git p7zip py27-speedtest-cli rsync stress tmux tree unrar unzip zfs-stats-lite zip nmap vim-lite"
 ESSENTIAL_JAIL_PACKAGES="axel bash bash-completion bsdadminscripts cpdup curl portmaster rsync tree unrar unzip zip vim-lite"
@@ -55,8 +55,11 @@ LRED="\033[1;31m"
 LGRN="\033[1;32m"
 LBLU="\033[1;34m"
 LCYN="\033[1;36m"
+CYAN="\033[0;36m"
 YELL="\033[1;33m"
 ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
 NRML="\033[0;00m"
 
 CARRIAGE_RETURN="
@@ -85,6 +88,8 @@ usage ()
   echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} setup-vnc-desktop${NRML}"
   echo -e ""
   echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} init-hotdesking${NRML}"
+  echo -e ""
+  echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} init-clonezilla-images${NRML}"
   echo -e ""
   echo -e ""
   echo -e "${LCYN}    ---- SCRIPT MANAGEMENT ----${NRML}"
@@ -134,6 +139,22 @@ usage ()
   echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} create-remote-desktop-instance template_name vnc_port_offset vnc_password${NRML}"
   echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} create-remote-desktop-instance Windows7 01 opensesame${NRML}"
   echo -e ""
+}
+
+pause_prompt ()
+{
+  # $[1} is the pause duration in seconds (maximum is 25).
+  PAUSE_DURATION=$(( ${1} * 10 ))
+  if [ ${PAUSE_DURATION} -gt 250 ]
+  then
+    PAUSE_DURATION=250
+  fi
+  echo -e "\n${GREY}Press any key to continue...${NRML}\c"  
+  CURRENT_TTY_SETTINGS=$(stty -g)
+  stty raw -echo min 0 time ${PAUSE_DURATION}
+  printf '%s' $(dd bs=1 count=1 2>/dev/null) > /dev/null
+  stty ${CURRENT_TTY_SETTINGS}
+  echo -e "\n"
 }
 
 question_yes_no ()
@@ -407,7 +428,7 @@ check_repo_config ()
     echo -e "${YELL}If this is your first host and you don't have a private remote git repo running${NRML}"
     echo -e "${YELL}yet. Then enter 'local' at the next prompt.${NRML}\n"
 
-    sleep 15
+    pause_prompt 25
 
     # Prompt for the type of repo to use, remote or local.
     REPO_TYPE=""
@@ -645,7 +666,7 @@ init_local_repo ()
   cd /
 
   # Clone or update the git repository
-  if [ -d /${REPO_NAME} ]
+  if [ -d "/${REPO_NAME}" ]
   then
 
     # The local repo already exists.
@@ -721,7 +742,7 @@ init_local_repo ()
 update_local_repo ()
 {
 
-  if [ ! -d /${REPO_NAME} ]
+  if [ ! -d "/${REPO_NAME}" ]
   then
     echo -e "\n${LRED}ERROR:${NRML} It appears the local git repo ('/${REPO_NAME}') does not exist!"
     echo -e "       ${LRED}Aborting.${NRML}\n"
@@ -1458,7 +1479,7 @@ new_host ()
 
   # Install essential packages
   echo -e "\n${YELL}Next we need to install some essential packages. Please accept when prompted...${NRML}\n"
-  sleep 5
+  pause_prompt 8
   pkg install ${ESSENTIAL_PACKAGES}
   if [ $? -ne 0 ]
   then   
@@ -1817,7 +1838,7 @@ new_host ()
         if [ "${LAN_IFACE_IP_TEMP}" = "" ]
         then
           echo -e "\n${LRED}ERROR:${NRML} No IP address selected! Try again.\n"
-          sleep 5
+          pause_prompt 5
         else
           question_yes_no "\n\nYou have selected '${LAN_IFACE_IP_TEMP}' as the LAN interface IP address.\nIs this correct?"
           if [ "${ANSWER}" = "yes" ]
@@ -2003,7 +2024,7 @@ new_host ()
 
   echo -e "\n${LGRN}Congratulations! We have now finished setting up the new host:${NRML}"
   echo -e "${LGRN}'${HOST_NAME}'.${NRML}\n\n" 
-  question_yes_no "Would you like to reboot now for new settings to take full effect\n[RECOMMENDED]"
+  question_yes_no "Would you like to reboot now for new settings to take full effect?\n[RECOMMENDED]"
   if [ "${ANSWER}" = "yes" ]
   then
     reboot
@@ -2103,7 +2124,7 @@ setup_vnc_desktop()
 
   # Install desktop / vnc packages
   echo -e "\n${YELL}Next we need to install some required packages. Please accept when prompted...${NRML}\n"
-  sleep 5
+  pause_prompt 8
   pkg install ${VNC_DESKTOP_PACKAGES}
   if [ $? -ne 0 ]
   then   
@@ -2578,7 +2599,7 @@ init_jails ()
   # Install essential package into the template jail
   echo -e "\n${YELL}Next we need to install some essential packages into the template jail.${NRML}"
   echo -e "${YELL}Please accept when prompted...${NRML}\n"
-  sleep 5
+  pause_prompt 8
   pkg -j template update
   pkg -j template install ${ESSENTIAL_JAIL_PACKAGES}
 
@@ -2650,7 +2671,7 @@ init_remote_desktops ()
 
   echo -e "\n${YELL}First we need to install some required packages.${NRML}"
   echo -e "${YELL}Please accept when prompted...${NRML}\n"
-  sleep 5
+  pause_prompt 8
   pkg update
   pkg install ${REMOTE_DESKTOP_PACKAGES}
 
@@ -2888,11 +2909,11 @@ create_remote_desktop_template ()
         LOOP=0
       else
         echo -e "\n\n${ORNG}WARNING:${NRML} File selected is not an ISO!\n"
-        sleep 5
+        pause_prompt 5
       fi
     else
       echo -e "\n\n${ORNG}WARNING:${NRML} No file selected!\n"
-      sleep 5
+      pause_prompt 5
     fi
   done
 
@@ -3003,11 +3024,11 @@ create_remote_desktop_template ()
           echo -e "\n\n${YELL}The selected ISO should now be inserted and available in the guest OS.${NRML}\n"
         else
           echo -e "\n\n${ORNG}WARNING:${NRML} File selected is not an ISO!\n"
-          sleep 5
+          pause_prompt 5
         fi
       else
         echo -e "\n\n${ORNG}WARNING:${NRML} No file selected!\n"
-        sleep 5
+        pause_prompt 5
       fi
     fi
   done
@@ -3346,7 +3367,7 @@ revert_create_jail ()
 
   # Stop the jail
   service jail stop ${JAIL_TO_REVERT}
-  sleep 5
+  sleep 10 
   jls | tail -n +2 | awk '{print $3}' | egrep "${JAIL_TO_REVERT}" > /dev/null 2>&1
   if [ ${?} -eq 0 ]
   then
@@ -3495,7 +3516,7 @@ create_jail_from_recipe ()
     for SERVICE in ${START_JAIL_SERVICES}
     do
       start_jail_service ${JAIL_NAME} ${SERVICE} --allow-restart
-      sleep 5
+      sleep 3
     done
 
   elif [ "${RECIPE_SUCCESS}" = "no" ]
@@ -3671,6 +3692,124 @@ init_clonezilla_images ()
 
 }
 
+merge_local_repo_to_remote ()
+{
+  # Test that we are actually using a local repo
+  if [ "${REPO_URI}" != "local" ]
+  then
+    echo -e "\n${LRED}ERROR:${NRML} It appears you are already using a remote repo!"
+    echo -e "       Aborting."
+    exit 180
+  fi
+
+  # Ask for the URI of the remote repo.
+  REMOTE_REPO_URI=""
+  while [ "${REMOTE_REPO_URI}" = "" ]
+  do
+    echo -e "\n${LCYN}Enter the remote git repo URI:${NRML}"
+    read REMOTE_REPO_URI_TEMP
+    # Allow use to change their mind about type of repo
+    if [ "${REMOTE_REPO_URI_TEMP}" = "" ]
+    then
+      break
+    fi
+    # Test the input to see if it is a valid URI (URL)
+    test_valid_simple_url "${REMOTE_REPO_URI_TEMP}"
+    if [ "${VALID_URL}" = "yes" ]
+    then
+      question_yes_no "\nYou have entered '${REMOTE_REPO_URI_TEMP}'\nas the remote git repo URI.\nIs this correct?"
+      if [ "${ANSWER}" = "yes" ]
+      then
+        REMOTE_REPO_URI=${REMOTE_REPO_URI_TEMP}
+      fi
+    else
+      echo -e "\n${LRED}ERROR:${NRML} remote git repo URI is invalid!\n"
+    fi
+  done
+
+  # Check that the remote repo is valid and that this hostname does not already exist. 
+  cd /tmp
+  rm -rf "${REPO_NAME}"
+  echo -e "\n${YELL}We need to check that this host does not already exist in the remote repo.${NRML}"
+  echo -e "${YELL}Please enter the remote repo credentials when prompted...${NRML}\n"
+  git clone "${REMOTE_REPO_URI}" "${REPO_NAME}"
+  if [ ${?} -ne 0 ]
+  then
+    echo -e "\n${LRED}ERROR:${NRML} Unable to clone the remote repo!"
+    echo -e "       Aborting."
+    exit 181
+  fi
+  if [ ! -d "${REPO_NAME}/configs/" ]
+  then
+    echo -e "\n${ORNG}WARNING:${NRML} The remote repo does not contain a config directory."
+	echo -e "         This usually means that it is a newly created, empty repo.\n"
+  elif [ -d  "${REPO_NAME}/configs/${HOST_NAME}" ]
+  then
+    rm -rf "${REPO_NAME}"
+    echo -e "\n${LRED}ERROR:${NRML} This host already exists in the remote repo!"
+	echo -e "       Consider removing or renaming the stale host config directory in the"
+    echo -e "   	remote repo."
+    echo -e "       Aborting."
+    exit 182
+  else
+    echo -e "\n${LGRN}The remote repo seems to be ok!${NRML}\n"
+  fi
+  rm -rf "${REPO_NAME}"
+
+  # Move into the local repo.
+  cd "/${REPO_NAME}"
+
+  ## TODO: check for existing remote in the local repo; warn and ask to proceed
+
+  # Add the remote repo URI as this local repos' remote.
+  git remote add origin "${REMOTE_REPO_URI}" > /dev/null 2>&1
+  if [ ${?} -ne 0 ]
+  then
+    echo -e "\n${LRED}ERROR:${NRML} Unable to add the remote repo as the origin!"
+    echo -e "       Aborting."
+    exit 183
+  fi
+
+  # Fetch the remote repo.
+  echo -e "\n${YELL}Next we need to fetch the remote repo into our local repo.${NRML}"
+  echo -e "${YELL}Please enter the remote repo credentials when prompted...${NRML}\n"
+  git fetch
+  if [ ${?} -ne 0 ]
+  then
+    echo -e "\n${LRED}ERROR:${NRML} Unable to fetch the remote repo (origin/master)!"
+    echo -e "       Aborting."
+	git remote remove origin
+    exit 184
+  fi
+
+  # Align the master branch on both local and remote repo.
+  git branch --set-upstream-to=origin/master master > /dev/null 2>&1
+  if [ ${?} -ne 0 ]
+  then
+	# The remote repo must be new / empty and so no master branch exists yet. So let's just push.
+    echo -e "\n${YELL}Next we need to pull the remote repo into our local repo.${NRML}"
+    echo -e "${YELL}Please enter the remote repo credentials when prompted...${NRML}\n"
+    git pull
+  else
+    # Perform a merge of the local and remote master branch
+    echo -e "\n${YELL}Next we need to merge the remote repo and our local repo...${NRML}\n"
+	pause_prompt 8
+	git merge -m "Merging local repo from host '${HOST_NAME}'."
+	## TODO: test for failure and clean up, inform user and exit
+  fi
+
+  # Lastly, push the local repo deltas to the remote repo.
+  echo -e "\n${YELL}Now we need to push the local repo changes to the remote repo.${NRML}"
+  echo -e "${YELL}Please enter the remote repo credentials when prompted...${NRML}\n"
+  git push
+  ## TODO: test for failure and clean up, inform user and exit
+
+  REPO_URI="${REMOTE_REPO_URI}"
+  echo "${REPO_URI}" >  "${FDO_CONFIG_ROOT}/fdo-server-repo.conf"
+  
+  echo -e "\n\n${LGRN}Congratulations! Successfully merged his hosts local repo to the remote repo.${NRML}\n"
+
+}
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -3806,6 +3945,12 @@ case ${SUB_CMD} in
     # Initialise the NFS share for Clonezilla images.
     update_local_repo
     init_clonezilla_images
+    ;;
+
+  merge-local-repo-to-remote)
+    # Move and merge a local repo to a private remote repo
+    update_local_repo
+    merge_local_repo_to_remote
     ;;
 
   init-jails)
