Add check for root (super-user) privileges.

diff --git a/fdo-server b/fdo-server
--- a/fdo-server
+++ b/fdo-server
@@ -10197,6 +10197,13 @@ init_partimag ()
 
 ##### MAIN EXECUTION THREAD ####################################################
 
+# Check we are running with root privileges.
+if [ `id -u` -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
+	exit 1
+fi
+
 TERM=${TERM}
 
 SUB_CMD="${1}"
